# Generated by Django 6.1.1 on 2026-09-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lab_id', models.CharField(blank=True, default='', max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(db_index=True, max_length=128)),
                ('mode', models.CharField(choices=[('practice', 'Practice'), ('exam', 'Exam')], max_length=16)),
                ('presented_order', models.JSONField(blank=True, default=list)),
                ('selected_ids', models.JSONField(default=list)),
                ('correct', models.BooleanField()),
                ('assisted', models.BooleanField(default=False)),
                ('is_first_exam_attempt', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['question_id', 'mode'], name='workbook_at_questio_df14cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(db_index=True, max_length=64)),
                ('checkpoint_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('not-started', 'Not started'), ('self-reported', 'Self-reported'), ('unresolved', 'Unresolved')], default='not-started', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('lab_id', 'checkpoint_id')},
            },
        ),
    ]
